In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6],int)
print(arr)

[1 2 3 4 5 6]


In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,4],[3,4,5]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 4]
  [3 4 5]]]


In [9]:
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [11]:
arr[1]

2

In [16]:
arr2[0,2] = 12
print(arr2)

[[ 1  2 12]
 [ 4  5  6]]
[[ 1  2 12]
 [ 4  5  6]]


In [21]:
arr0 = np.zeros((3,3))
print(arr0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
ar1 = np.ones((2,2))
print(ar1)

[[1. 1.]
 [1. 1.]]


In [28]:
arr = np.random.randint(1,10,size = 11)
arr

array([9, 9, 3, 2, 6, 8, 2, 5, 6, 4, 6])

In [30]:
arr = np.random.rand(3,3)
arr

array([[0.61894188, 0.52293101, 0.53114199],
       [0.98221298, 0.43754612, 0.77452484],
       [0.08874301, 0.90814263, 0.19173576]])

In [35]:
arr = np.random.choice(['A','B','C'], size = 10)
for i in arr:
    print(i)

B
C
C
A
A
B
C
B
A
A


In [36]:
arr = np.random.randint(1,10,size = 10)
arr

array([2, 6, 3, 9, 3, 2, 6, 9, 3, 7])

In [37]:
arr.mean()

5.0

In [40]:
arr.sum()

50

In [41]:
arr.max()

9

In [42]:
arr.min()

2

In [43]:
arr.argmin()

0

In [45]:
arr.argmax()

3

In [46]:
arr[0] = 10

In [47]:
arr.argmin()

5

In [50]:
arr = np.array([[1,2,3],[2,3,4]])
for i in arr:
    print(i)

[1 2 3]
[2 3 4]


In [51]:
arr = np.array(list(map(int , input().split())))

 12 15 23


In [52]:
arr

array([12, 15, 23])

In [58]:
row = int(input())
arr = np.array([list(map(int, input().split())) for i in range(row)])

 5
 1 2 3 1
 1 2 5 6
 1 4 7 8
 2 5 6 9
  3 5 6 9


In [59]:
arr

array([[1, 2, 3, 1],
       [1, 2, 5, 6],
       [1, 4, 7, 8],
       [2, 5, 6, 9],
       [3, 5, 6, 9]])

In [61]:
arr = np.empty((3,2))

In [62]:
arr

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.06810200e-306],
       [1.89146896e-307, 7.56571288e-307]])

In [64]:
val = np.arange(1,10)
val

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
val = np.linspace(1,10,5)
val

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [70]:
row = int(input())
arr = np.array([list(map(int, input().split())) for i in range(row)])
arr = arr.reshape(3,3)
arr

 9
 1
 2
 3
 4
 5
 6
 7
 8
 9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [78]:
np.ravel(arr)
dup = np.eye(3)
dup

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
import random

In [106]:
val = np.full((3,3), fill_value = random.choice([1,2,4]))
val

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [116]:
arr1 = np.array([1,2,4])
arr2 = np.arange(1,4)

In [ ]:
arr1 = np.concatenate((arr1,arr2))
arr1

In [117]:
arr1.dot(arr2)

17

In [121]:
val = np.power(arr1,arr2)
val

array([ 1,  4, 64])

In [125]:
arr = np.arange(1,10)
arr.shape

(9,)

In [127]:
val = arr.copy()
val

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
arr = arr.astype(int)
type(arr[0])

numpy.int32

In [140]:
arr = np.array([1,2,2,2,3,4,4,4])
val = np.unique(arr)
val

array([1, 2, 3, 4])